### ISSUE TITLE
NPM build issue

### ISSUE THREAD

**Issue by ednsinf** [RaythaHQ/raytha#207]
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	MSB3073	The command "npm install" exited with code -4048.	Raytha.Web	C:\Users\xxx\Downloads\raytha-1.3.0\src\Raytha.Web\Raytha.Web.csproj	69	
Error (active)	[Error	EPERM: operation not permitted, unlink 'C:\Users\xxx\AppData\Local\npm-cache\_cacache\tmp\44f83f56'] {	Raytha.Web	C:\Users\xxx\Downloads\raytha-1.3.0\src\Raytha.Web\EXEC	1	
Error (active)	errno	-4048,	Raytha.Web	C:\Users\xxx\Downloads\raytha-1.3.0\src\Raytha.Web\EXEC	1	
Error (active)	syscall	'unlink',	Raytha.Web	C:\Users\xxx\Downloads\raytha-1.3.0\src\Raytha.Web\EXEC	1	
Error (active)	code	'EPERM',	Raytha.Web	C:\Users\xxx\Downloads\raytha-1.3.0\src\Raytha.Web\EXEC	1	
Error (active)	path	'C:\\Users\\xxx\\AppData\\Local\\npm-cache\\_cacache\\tmp\\44f83f56'	Raytha.Web	C:\Users\xxx\Downloads\raytha-1.3.0\src\Raytha.Web\EXEC	1

**Comment by apexdodge** [comment]
ChatGPT suggests that it could be a permissions issue with your local setup. You would have to look at that further.

Alternatively, you could navigate to the src\Raytha.Web\wwwroot\raytha_admin\js directory and run the npm commands as one normally would to build their front end javascript.

```
npm install
npm run build
```
Then in VS you can run it without compiling the javascript by choosing `Debug without JS`

![image](https://github.com/user-attachments/assets/ec8bfa6f-b5f9-4eba-b4ef-ffe83d1d18f8)

And your github issue title was edited due to being rude and unprofessional.
